import {
  Atom,
  FileCode,
  Layers,
  Palette,
  Triangle,
  Flame,
  Hexagon,
  Database,
  Share2,
  Zap,
  Braces,
  Layers3,
  Container,
  GitBranch,
  Cloud,
  GitMerge,
  Boxes,
  PenTool,
  Monitor,
  Server,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/src/types";

export const skillIcons: Record<IconName, LucideIcon> = {
  atom: Atom,
  "file-code": FileCode,
  layers: Layers,
  palette: Palette,
  triangle: Triangle,
  flame: Flame,
  hexagon: Hexagon,
  database: Database,
  "share-2": Share2,
  zap: Zap,
  braces: Braces,
  "layers-3": Layers3,
  container: Container,
  "git-branch": GitBranch,
  cloud: Cloud,
  "git-merge": GitMerge,
  boxes: Boxes,
  figma: PenTool,
  monitor: Monitor,
  server: Server,
  wrench: Wrench,
};
